spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
    username: ara
    password: ara1234

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDBDialect # DB Dialect(??) ??

  mybatis:
    mapper-locations: classpath:mapper/*.xml